### ISSUE TITLE
Can't get a quote using curl

### ISSUE THREAD

**Issue by erhanalankus** [ajzbc/kanye.rest#19]
In bash, I used to type

`curl api.kanye.rest`

and it returned a quote. But for the last couple of days, this command does not return a quote.

<br>
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Linux erhan-desktop 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ajzbc** [comment]
I am unable to reproduce this problem. `curl api.kanye.rest` is working fine for me.
Can you send me an error message or something to go off of?

**Comment by erhanalankus** [comment]
Nothing happened when I tried before.
But now I tried again and it works. Maybe something went wrong with my pc.
I'm loving your API and I'm telling everyone about it :)

"today is the best day ever and tomorrow's going to be even better"

**Comment by ajzbc** [comment]
After you said it didn't work I did turn off forced https on Cloudflare, but I was unable to test curl until after I did that since I was on my phone. That may have been the issue.

I'm glad you are liking it!

Just FYI I am unfortunately planning on changing up some of the endpoints a bit. The default endpoint of 'https://api.kanye.rest' will respond with plain text, and there will be another endpoint for a JSON response. This is just to simplify stuff since it is a very basic API. However, I will provide ample notice of this change on the main site, so make sure to check every few days.
